server:
  port: 0
  
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/eka
    username: root
    password: Novotna@123
  
  
  application:
    name: AdminLogin  
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

pivotal:
  emplogin:
    name: EmployeeLogin
        